import bcrypt from 'bcryptjs';

const users = [
  {
    firstName: 'hello',
    lastName: '260',
    email: 'admin@hello260.com',
    password: bcrypt.hashSync('admin@pass', 10),
    isAdmin: true,
  },
  {
    firstName: 'Kamilla',
    lastName: 'Hejlikova',
    email: 'kamilla@hello260.com',
    password: bcrypt.hashSync('kamilla@pass', 10),
    isAdmin: true,
  },
  {
    firstName: 'Oneous',
    lastName: 'Mality',
    email: 'mality@hello260.com',
    password: bcrypt.hashSync('mality@pass', 10),
  },
  {
    firstName: 'Martin',
    lastName: 'Nyemba',
    email: 'martin@hello260.com',
    password: bcrypt.hashSync('martin@pass', 10),
  },
];

const products = [
  {
    name: 'Pure Mungongo Oil 30ml',
    price: 75,
    description: 'Pure and natural Mungongo oil in a convenient 30ml size, rich in antioxidants and essential fatty acids.',
    ingredients: '100% pure, cold-pressed Mungongo (Schinziophyton rautanenii) seed oil.',
    benefits: 'Deeply moisturizes, nourishes skin and hair, rich in vitamin E, linoleic acid, and eleostearic acid. Helps reduce fine lines and improves skin elasticity.',
    size: '30ml',
    howToUse: 'Apply a few drops to clean, damp skin or hair. Gently massage until absorbed. Use daily for best results. Can be used on face, body, and hair.',
    category: 'oil',
    image: 'mungongo-oil-30ml',
    countInStock: 20,
    rating: 4.8,
    numReviews: 12,
    featured: true,
  },
  {
    name: 'Pure Mungongo Oil 50ml',
    price: 120,
    description: 'Pure and natural Mungongo oil in a 50ml size.',
    ingredients: '100% pure, cold-pressed Mungongo (Schinziophyton rautanenii) seed oil.',
    benefits: 'Deeply moisturizes, nourishes skin and hair, rich in vitamin E, linoleic acid, and eleostearic acid. Helps reduce fine lines and improves skin elasticity.',
    size: '50ml',
    howToUse: 'Apply a few drops to clean, damp skin or hair. Gently massage until absorbed. Use daily for best results. Can be used on face, body, and hair.',
    category: 'oil',
    image: 'mungongo-oil-50ml',
    countInStock: 15,
    rating: 4.7,
    numReviews: 8,
    featured: false,
  },
  {
    name: 'Pure Mungongo Oil 100ml',
    price: 180,
    description: 'Pure and natural Mungongo oil in a larger 100ml size.',
    ingredients: '100% pure, cold-pressed Mungongo (Schinziophyton rautanenii) seed oil.',
    benefits: 'Deeply moisturizes, nourishes skin and hair, rich in vitamin E, linoleic acid, and eleostearic acid. Helps reduce fine lines and improves skin elasticity.',
    size: '100ml',
    howToUse: 'Apply a few drops to clean, damp skin or hair. Gently massage until absorbed. Use daily for best results. Can be used on face, body, and hair.',
    category: 'oil',
    image: 'mungongo-oil-100ml',
    countInStock: 10,
    rating: 4.9,
    numReviews: 15,
    featured: true,
  },
  {
    name: 'Pure Mungongo Oil 200ml',
    price: 250,
    description: 'Our largest size of pure Mungongo oil at 200ml.',
    ingredients: '100% pure, cold-pressed Mungongo (Schinziophyton rautanenii) seed oil.',
    benefits: 'Deeply moisturizes, nourishes skin and hair, rich in vitamin E, linoleic acid, and eleostearic acid. Helps reduce fine lines and improves skin elasticity.',
    size: '200ml',
    howToUse: 'Apply a few drops to clean, damp skin or hair. Gently massage until absorbed. Use daily for best results. Can be used on face, body, and hair.',
    category: 'oil',
    image: 'mungongo-oil-200ml',
    countInStock: 8,
    rating: 5.0,
    numReviews: 7,
    featured: true,
  },
  {
    name: 'Mungongo Lotion 30ml',
    price: 175,
    description: 'Hydrating lotion made with Mungongo oil.',
    ingredients: 'Purified water, Mungongo oil, glycerin, cetearyl alcohol, glyceryl stearate, shea butter, aloe vera extract, vitamin E, phenoxyethanol, natural fragrance.',
    benefits: 'Hydrates and softens skin, promotes smooth and supple texture, helps maintain skin moisture balance, absorbs quickly without greasy residue.',
    size: '30ml',
    howToUse: 'Apply to clean skin and massage gently until absorbed. Use daily after bathing for best results. Suitable for all skin types.',
    category: 'lotion',
    image: 'mungongo-lotion',
    countInStock: 25,
    rating: 4.6,
    numReviews: 9,
    featured: false,
  },
  {
    name: 'Baobab Lotion 30ml',
    price: 175,
    description: 'Nourishing lotion made with Baobab oil.',
    ingredients: 'Purified water, Baobab oil, glycerin, cetearyl alcohol, glyceryl stearate, shea butter, aloe vera extract, vitamin E, phenoxyethanol, natural fragrance.',
    benefits: 'Rich in vitamins A, D, E, and F, deeply nourishes skin, improves skin elasticity, provides exceptional moisturization for dry skin.',
    size: '30ml',
    howToUse: 'Apply to clean skin and massage gently until absorbed. Use daily after bathing for best results. Especially beneficial for dry or mature skin.',
    category: 'lotion',
    image: 'baobab-lotion',
    countInStock: 25,
    rating: 4.5,
    numReviews: 6,
    featured: false,
  },
  {
    name: 'Molinga Lotion 30ml',
    price: 175,
    description: 'Revitalizing lotion made with Molinga extract.',
    ingredients: 'Purified water, Moringa seed oil, glycerin, cetearyl alcohol, glyceryl stearate, shea butter, aloe vera extract, vitamin E, phenoxyethanol, natural fragrance.',
    benefits: 'Rich in antioxidants, helps clear impurities, soothes inflammation, supports skin rejuvenation, provides natural antibacterial properties.',
    size: '30ml',
    howToUse: 'Apply to clean skin and massage gently until absorbed. Use daily after bathing for best results. Excellent for problematic or sensitive skin.',
    category: 'lotion',
    image: 'molinga-lotion',
    countInStock: 25,
    rating: 4.4,
    numReviews: 5,
    featured: false,
  },
  {
    name: 'Pure Mungongo Body Scrub',
    price: 175,
    description: 'Natural exfoliating body scrub made with pure Mungongo.',
    ingredients: 'Sugar, Mungongo oil, shea butter, vitamin E, essential oil blend.',
    benefits: 'Gently exfoliates dead skin cells, promotes circulation, leaves skin soft and smooth, prepares skin for moisturization.',
    size: '200g',
    howToUse: 'Apply to damp skin in circular motions. Rinse thoroughly with warm water. Use 1-2 times weekly. Follow with moisturizer for best results.',
    category: 'body-care',
    image: 'pure-mungongo-scrub',
    countInStock: 20,
    rating: 4.7,
    numReviews: 10,
    featured: true,
  },
  {
    name: 'Mungongo & Baobab Body Scrub',
    price: 175,
    description: 'Luxurious body scrub combining Mungongo and Baobab.',
    ingredients: 'Sugar, Mungongo oil, Baobab oil, shea butter, vitamin E, essential oil blend.',
    benefits: 'Dual-action exfoliation and deep nourishment, promotes skin cell renewal, provides intense hydration, leaves skin incredibly soft.',
    size: '200g',
    howToUse: 'Apply to damp skin in circular motions. Rinse thoroughly with warm water. Use 1-2 times weekly. Follow with moisturizer for best results.',
    category: 'body-care',
    image: 'mungongo-baobab-scrub',
    countInStock: 20,
    rating: 4.8,
    numReviews: 12,
    featured: true,
  },
  {
    name: 'Mungongo, Baobab & Molinga Body Scrub',
    price: 175,
    description: 'Triple-action body scrub combining Mungongo, Baobab and Molinga.',
    ingredients: 'Sugar, Mungongo oil, Baobab oil, Moringa extract, shea butter, vitamin E, essential oil blend.',
    benefits: 'Triple-action formula exfoliates, nourishes, and revitalizes. Combines the power of three superfoods for ultimate skin rejuvenation.',
    size: '200g',
    howToUse: 'Apply to damp skin in circular motions. Rinse thoroughly with warm water. Use 1-2 times weekly. Follow with moisturizer for best results.',
    category: 'body-care',
    image: 'triple-blend-scrub',
    countInStock: 15,
    rating: 4.9,
    numReviews: 8,
    featured: true,
  },
  {
    name: 'Mungongo & Lavender Oil 100ml',
    price: 175,
    description: 'Soothing blend of Mungongo oil and lavender essential oil.',
    ingredients: 'Mungongo oil, lavender essential oil.',
    benefits: 'Calming and relaxing properties, helps reduce stress and anxiety, promotes restful sleep, soothes skin irritations.',
    size: '100ml',
    howToUse: 'Apply to skin as a body oil, add a few drops to bath water, or use for massage. Can also be used as a hair treatment or to create a relaxing atmosphere when diffused.',
    category: 'essentials',
    image: 'mungongo-lavender',
    countInStock: 20,
    rating: 4.6,
    numReviews: 9,
    featured: false,
  },
  {
    name: 'Mungongo & Tea Tree Oil 100ml',
    price: 175,
    description: 'Purifying blend of Mungongo oil and tea tree essential oil.',
    ingredients: 'Mungongo oil, tea tree essential oil.',
    benefits: 'Natural antibacterial and antifungal properties, helps clear blemishes, soothes skin irritations, promotes healthy scalp and hair.',
    size: '100ml',
    howToUse: 'Apply sparingly to affected areas of skin. Can be used as a spot treatment for blemishes or as a scalp treatment. Dilute further if sensitivity occurs.',
    category: 'essentials',
    image: 'mungongo-tea-tree',
    countInStock: 20,
    rating: 4.5,
    numReviews: 7,
    featured: false,
  },
  {
    name: 'Mungongo & Eucalyptus Oil 30ml',
    price: 100,
    description: 'Refreshing blend of Mungongo oil and eucalyptus essential oil in 30ml.',
    ingredients: 'Mungongo oil, eucalyptus essential oil.',
    benefits: 'Opens airways and promotes clear breathing, refreshes and invigorates, helps relieve muscle tension, provides natural cooling sensation.',
    size: '30ml',
    howToUse: 'Apply to chest, neck, or temples for respiratory benefits. Use as a massage oil for sore muscles. Add a few drops to hot shower for spa-like experience.',
    category: 'essentials',
    image: 'mungongo-eucalyptus-30ml',
    countInStock: 25,
    rating: 4.6,
    numReviews: 6,
    featured: false,
  },
  {
    name: 'Mungongo & Eucalyptus Oil 100ml',
    price: 200,
    description: 'Refreshing blend of Mungongo oil and eucalyptus essential oil in 100ml.',
    ingredients: 'Mungongo oil, eucalyptus essential oil.',
    benefits: 'Opens airways and promotes clear breathing, refreshes and invigorates, helps relieve muscle tension, provides natural cooling sensation.',
    size: '100ml',
    howToUse: 'Apply to chest, neck, or temples for respiratory benefits. Use as a massage oil for sore muscles. Add a few drops to hot shower for spa-like experience.',
    category: 'essentials',
    image: 'mungongo-eucalyptus-100ml',
    countInStock: 15,
    rating: 4.7,
    numReviews: 8,
    featured: true,
  },
  {
    name: 'Mungongo & Baobab Oil 30ml',
    price: 100,
    description: 'Nourishing blend of Mungongo and Baobab oils in 30ml.',
    ingredients: 'Mungongo oil, Baobab oil.',
    benefits: 'Powerful combination of two African superfoods, provides intense hydration, rich in vitamins and antioxidants, suitable for face, body, and hair.',
    size: '30ml',
    howToUse: 'Apply a few drops to face, body, or hair. Can be used as a daily moisturizer, hair treatment, or added to bath water for a luxurious soak.',
    category: 'essentials',
    image: 'mungongo-baobab-30ml',
    countInStock: 25,
    rating: 4.8,
    numReviews: 10,
    featured: true,
  },
];

export { users, products }; 